ballerina-platform/module-ballerinax-microsoft.excel

README.md
src/microsoft.sheets/Module.md

There are some documentation issues to be fixed. Most of them were caused because of the use of angular brackets to indicate configuration parameters. Furthermore, some of the code refactoring changes did not reflect in the documentation properly.
Improve the documentation by fixing the bugs.
N/A
N/A
N/A
N/A
N/A
N/A
N/A
N/A
N/A
N/A
N/A
N/A
N/A

Fix documentation issues

---

Ballerina.toml
src/microsoft.sheets/spreadsheet_endpoint.bal
src/microsoft.sheets/tests/main_test.bal

This will fix few minor code style issues
Conduct minor code refactoring
N/A
N/A
N/A
N/A
N/A
N/A
N/A
N/A
N/A
N/A
N/A
JDK 1.8, Ubuntu 18.04
N/A

Apply minor code refactoring

---

Ballerina.lock
Ballerina.toml

Update the version number to match with the API change which has been done in the config.
Update the version number to match with the API change which has been done in the config.
N/A
N/A
N/A
N/A
N/A
N/A
N/A
N/A
N/A
N/A
N/A
N/A
N/A

Update the version number

---

excel/Ballerina.toml

Update connector version

---

excel/Dependencies.toml
excel/client.bal
excel/constants.bal
excel/tests/test.bal
excel/types.bal
excel/utils.bal

Add session support for client operations

---

README.md
excel/Dependencies.toml
excel/Package.md

- Bump version to slbeta3 in Dependencies.toml, README.md and Package.md
JDK 11
Ballerina SLBeta3-SNAPSHOT

Bump versions for slbeta3 in master branch

---

excel/client.bal
excel/tests/test.bal

$subject
JDK 11
Ballerina SL Beta2
Ubuntu 20.04

Fix missing session support in client operaions

---

excel/tests/test.bal

$subject
JDK 11
Ballerina SL Beta3-SNAPSHOT
Ubuntu 20.04

Fix delete table test case

---

excel/Dependencies.toml
gradle.properties

$title
JDK 11
Ballerina SLBeta3

Bump dependency versions for Ballerina SLBeta3

---

.github/workflows/ci.yml
.github/workflows/daily-build.yml
.github/workflows/pull-request.yml
.github/workflows/release.yml
README.md
excel/Dependencies.toml

Related https://github.com/ballerina-platform/ballerina-extended-library/issues/128
One line release note: 
- Add slbeta4 migration changes
**Test Configuration**:
* Ballerina Version: Ballerina swan lake beta 4
* Operating System: Ubuntu (Linux)
* Java SDK: Java 11

Add slbeta 4 migration changes

---

README.md
excel/Ballerina.toml
excel/Dependencies.toml
excel/Package.md
gradle.properties

- Bump version to `2.1.0`
- Update Ballerina version to `SLBeta6` in Package.md 
- Regenerate Dependencies.toml with `SLBeta6`
- Add `distribution = "slbeta6"` in Ballerina.toml

Prepare for 2.1.0 release with SLBeta6

---

excel/Dependencies.toml

- Update Dependencies.toml with latest standard library versions

Re-generate Dependencies.toml with latest pack

---

excel/Ballerina.toml
excel/Dependencies.toml
excel/Package.md
gradle.properties

https://github.com/ballerina-platform/ballerina-extended-library/issues/265
- Bump version to `2.2.0`
- Update Ballerina version to `2201.0.0` in Package.md 
- Regenerate Dependencies.toml with `2201.0.0`
- Add `distribution = "2201.0.0"` in Ballerina.toml

prepare for 2.2.0 release with ballerina 2201.0.0

---

excel/client.bal

Fix documentation indentation

---

excel/Ballerina.toml
excel/Dependencies.toml
excel/Package.md
excel/client.bal
excel/config-types.bal

Revamp connector 
related [#14865](https://github.com/wso2-enterprise/choreo/issues/14865)
**Test Configuration**:
* Ballerina Version: Ballerina 2201.2.0
* Operating System: Ubuntu
* Java SDK: Java 11

Revamp connector #14865

---

excel/client.bal
excel/config-types.bal

Related https://github.com/wso2-enterprise/choreo/issues/14865
Related https://github.com/wso2-enterprise/choreo/issues/15133
**Test Configuration**:
* Ballerina Version: Ballerina 2201.2.0
* Operating System: Ubuntu
* Java SDK: Java 11

fix #15133

---

README.md
excel/Package.md

$Subject
Fixes # https://github.com/ballerina-platform/ballerina-extended-library/issues/474

Update Slack channel occurrences with Discord

---

excel/Ballerina.toml
excel/Dependencies.toml
excel/Package.md

$Subject
Fixes # https://github.com/ballerina-platform/ballerina-extended-library/issues/475

Update to Ballerina version 2201.3.0

---

excel/tests/test.bal

$Subject. Incorrect test dependencies have made the tests to fail.  
Related issue: https://github.com/wso2-enterprise/choreo/issues/16598

Fix daily build by correcting test dependecies

---

.github/CODEOWNERS
examples/update_chart.bal

Fix daily build failure and update module owners
